name: GitHub Actions
on: [push]
jobs:
  init: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 21.x ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Node.js version check
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: yarn
      - name: Check jest unit tests 
        run: yarn test:unit
          

